---
- name: AWS Infrastructure Management
  hosts: localhost
  gather_facts: true
  vars:
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    instance_type: "t2.small"
    # ami_id: "ami-0a0bff6476c1e1cb4"  # Example AMI for Amazon Linux 2
    region: "ap-south-1"
    key_name: "anshul-test"  # Replace with your key pair
    teardown: true  # Set to true for teardown
    tag_name: "anshul-aws-resources"
  vars_files:
    - ami_mapping.yml
  tasks:
    - name: Set AMI ID based on region and OS version
      ansible.builtin.set_fact:
        ami_id: "{{ ami_mapping[region][ami_os] }}"

    - name: Set teardown boolean based on survey input
      ansible.builtin.set_fact:
        teardown: "{{ teardown_mapping[survey_teardown_response | lower] }}"

    - name: Search for existing VPC
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ tag_name }}-vpc"
        region: "{{ region }}"
      register: vpc_info

    - name: Create VPC if not exists
      amazon.aws.ec2_vpc_net:
        name: "{{ tag_name }}-vpc"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        tags:
          Name: "{{ tag_name }}-vpc"
      when: vpc_info.vpcs | length == 0 and not teardown
      register: vpc

    - name: Use existing VPC
      ansible.builtin.set_fact:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      when: vpc_info.vpcs | length > 0 and not teardown

    - name: Create Subnet if not exists
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id | default(vpc.vpc.id) }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        tags:
          Name: "{{ tag_name }}-subnet"
      when: not teardown
      register: subnet

    - name: Create Internet Gateway if not exists
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id | default(vpc.vpc.id) }}"
        region: "{{ region }}"
        tags:
          Name: "{{ tag_name }}-igw"
      when: not teardown
      register: igw

    - name: Create Internet Gateway if not exists and attach to VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id | default(vpc.vpc.id) }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ tag_name }}-igw"
      when: not teardown
      register: igw

    - name: Create Security Group if not exists
      amazon.aws.ec2_security_group:
        name: "{{ tag_name }}-sg"
        description: "Security group for {{ tag_name }}"
        vpc_id: "{{ vpc_id | default(vpc.vpc.id) }}"
        region: "{{ region }}"
        tags:
          Name: "{{ tag_name }}-sg"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: "0.0.0.0/0"
      when: not teardown
      register: security_group

    # - name: Create Load Balancer if not exists
    #   amazon.aws.elb_application_lb:
    #     name: "{{ tag_name }}-elb"
    #     subnets:
    #       - "{{ subnet.subnet.id }}"
    #     security_groups:
    #       - "{{ security_group.group_id }}"
    #     scheme: internet-facing
    #     state: present
    #     region: "{{ region }}"
    #   when: not teardown
    #   register: load_balancer

    - name: Create EC2 Instance if not exists
      amazon.aws.ec2_instance:
        name: "{{ tag_name }}-instance"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        security_group: "{{ security_group.group_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ tag_name }}-instance"
      when: not teardown
      register: ec2_instance

    # - name: Create Volume if not exists
    #   amazon.aws.ec2_vol:
    #     region: "{{ region }}"
    #     zone: "{{ region }}a"
    #     volume_size: 10  # Size in GB
    #     volume_type: gp2
    #     device_name: /dev/sdf
    #   when: not teardown
    #   register: volume

    # - name: Attach Volume to EC2 Instance
    #   amazon.aws.ec2_vol:
    #     id: "{{ volume.volume_id }}"
    #     instance: "{{ ec2_instance.instances[0].instance_id }}"
    #     device_name: /dev/sdf
    #     region: "{{ region }}"
    #     state: present
    #   when: not teardown

    - name: Find EC2 instances by tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ tag_name }}-instance"
        region: "{{ region }}"
      register: ec2_info

    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
        region: "{{ region }}"
        state: absent
      when: teardown and ec2_info.instances | length > 0

    # - name: Teardown - Delete Load Balancer
    #   amazon.aws.elb_application_lb:
    #     name: "{{ load_balancer.load_balancer_name }}"
    #     region: "{{ region }}"
    #     state: absent
    #   when: teardown and load_balancer.load_balancer_name is defined

    - name: Find the Security Group by Name
      amazon.aws.ec2_security_group_info:
        filters:
          "tag:Name": "{{ tag_name }}-sg"
        region: "{{ region }}"
      register: security_group_info

    - name: Teardown - Delete Security Group
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_info.security_groups[0].group_id }}"
        region: "{{ region }}"
        state: absent
      when: teardown and security_group_info.security_groups | length > 0

    - name: Retrieve VPC Information
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ tag_name }}-vpc"  # Adjust the filter to match how your VPC is tagged
        region: "{{ region }}"
      register: vpc_info

    - name: Find Subnet by VPC and CIDR
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
          cidr-block: "{{ subnet_cidr }}"
        region: "{{ region }}"
      register: subnet_info

    - name: Set Subnet ID if Found
      ansible.builtin.set_fact:
        subnet_id: "{{ subnet_info.subnets[0].subnet_id }}"
      when: subnet_info.subnets | length > 0

    - name: Teardown - Delete Subnet
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "{{ subnet_cidr }}"
        state: absent
      when: teardown and subnet_id is defined

    - name: Detach Internet Gateway from VPC
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        state: absent
        region: "{{ region }}"
      when: teardown and vpc_info.vpcs | length > 0

    - name: Teardown - Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: teardown and vpc_info.vpcs | length > 0
