---
- name: AWS Infrastructure Management Test
  hosts: localhost
  gather_facts: true
  vars:
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    key_name: "anshul-test"
    instance_type: "t3.small"
    survey_teardown_response: "yes"
    tag_name: "anshul-aws-resources"
    ami_os: "RHEL8"
    region: "ap-south-1"
  roles:
    - testns270991.rhdhtest1234.run
