---
- name: AWS Infrastructure Management
  hosts: localhost
  gather_facts: true
  vars:
    vpc_cidr: 10.0.0.0/16
    subnet_cidr: 10.0.1.0/24
  vars_files:
    - mapping.yml
  roles:
    - testns270991.rhdhtest1234.run
